/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Component;
import java.awt.Font;
import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import yumxpress.dao.CompanyDAO;
import yumxpress.dao.PlaceOrderDAO;
import yumxpress.gui.OrderProductFrame;
import yumxpress.dao.ProductDAO;
import yumxpress.dao.StaffDAO;
import yumxpress.pojo.PlaceOrderPojo;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.UserProfile;

/**
 *
 * @author Smart computer
 */
public class OrderFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form OrderFoodFrame
     */
    int pos=-1;
    int track=0;
    int index;
    private Map<String,String> allSeller=new HashMap<>();
    private int foodIndex=0;
    private int loc=1;
    List<ProductPojo>pro=new ArrayList<>();
    //Map<String,ProductPojo> productDetails=new HashMap<>();
    public OrderFoodFrame() {
        initComponents();
        this.setTitle("OrderFoodFrame");
        this.setLocationRelativeTo(null);
        lblName.setText("HELLO "+UserProfile.getUserName());
        loadAllSeller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblleftclick = new javax.swing.JLabel();
        lblrightclick = new javax.swing.JLabel();
        lblfood1 = new javax.swing.JLabel();
        lblfoodname1 = new javax.swing.JLabel();
        lblfood2 = new javax.swing.JLabel();
        lblfoodname2 = new javax.swing.JLabel();
        lblfood3 = new javax.swing.JLabel();
        lblfoodname3 = new javax.swing.JLabel();
        lblfood4 = new javax.swing.JLabel();
        lblfoodname4 = new javax.swing.JLabel();
        lblfood5 = new javax.swing.JLabel();
        lblfoodname5 = new javax.swing.JLabel();
        lblfood6 = new javax.swing.JLabel();
        lblfoodname6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcballSellerName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnMyAccount = new javax.swing.JButton();
        btnMyCart = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblleftclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/icons8-left-arrow-64.png"))); // NOI18N
        lblleftclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblleftclickMouseClicked(evt);
            }
        });
        jPanel2.add(lblleftclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 340, 68, 62));

        lblrightclick.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/icons8-right-arrow-64.png"))); // NOI18N
        lblrightclick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblrightclickMouseClicked(evt);
            }
        });
        jPanel2.add(lblrightclick, new org.netbeans.lib.awtextra.AbsoluteConstraints(1011, 338, 66, -1));

        lblfood1.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood1MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 192, 211, 135));

        lblfoodname1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 351, 211, 39));

        lblfood2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood2MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 192, 211, 135));

        lblfoodname2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 352, 211, 39));

        lblfood3.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood3MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood3, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 192, 211, 135));

        lblfoodname3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname3, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 352, 211, 39));

        lblfood4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood4MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood4, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 421, 211, 135));

        lblfoodname4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname4, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 574, 211, 39));

        lblfood5.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood5MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 421, 211, 135));

        lblfoodname5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname5, new org.netbeans.lib.awtextra.AbsoluteConstraints(562, 572, 211, 39));

        lblfood6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        lblfood6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        lblfood6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblfood6MouseClicked(evt);
            }
        });
        jPanel2.add(lblfood6, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 421, 211, 135));

        lblfoodname6.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        lblfoodname6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.add(lblfoodname6, new org.netbeans.lib.awtextra.AbsoluteConstraints(791, 574, 211, 39));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 0));
        jLabel5.setText("FILTER");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 95, -1, 37));

        jcballSellerName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jcballSellerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcballSellerNameActionPerformed(evt);
            }
        });
        jPanel2.add(jcballSellerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 95, 217, 37));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 255));
        jLabel4.setText("Order Food");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 16, -1, -1));

        jPanel6.setBackground(new java.awt.Color(0, 138, 255));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N

        lblName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblName.setText("@null");

        btnMyAccount.setBackground(new java.awt.Color(255, 106, 99));
        btnMyAccount.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccountActionPerformed(evt);
            }
        });

        btnMyCart.setBackground(new java.awt.Color(255, 106, 99));
        btnMyCart.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMyCart.setText("My Cart");
        btnMyCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyCartActionPerformed(evt);
            }
        });

        btnCancelOrder.setBackground(new java.awt.Color(255, 106, 99));
        btnCancelOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCancelOrder.setText("Cancel Order");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });

        btnOrderHistory.setBackground(new java.awt.Color(255, 106, 99));
        btnOrderHistory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnOrderHistory.setText("Order History");
        btnOrderHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderHistoryActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblName))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblName)
                .addGap(7, 7, 7)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnMyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnMyCart, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnCancelOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnOrderHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcballSellerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcballSellerNameActionPerformed
        // TODO add your handling code here:
        String selectedSeller=jcballSellerName.getSelectedItem()+"";
        try{
            if(selectedSeller.equals("ALL")){
                pro=ProductDAO.getAllProducts(selectedSeller);//list of productpojo
            }
            else{
                pro=ProductDAO.getAllProducts(allSeller.get(selectedSeller));//list of productpojo   
            }
            foodIndex=0;
            loc=1;
            clearAll();
            setNA();
            showAllFood(pro);
        }catch(SQLException sq){
            JOptionPane.showMessageDialog(null,"DB Error in Order Food Frame display");
            return;
        }
         catch(IOException sq){
            JOptionPane.showMessageDialog(null,"I/O Error in Order Food Frame");
            return;
        }
    }//GEN-LAST:event_jcballSellerNameActionPerformed

    private void lblrightclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblrightclickMouseClicked
        // TODO add your handling code here:
        loc=1;
        foodIndex=index;
        if(foodIndex>=pro.size()){
            JOptionPane.showMessageDialog(null,"You Explore All Food By Right Side");
            return;
        }
        clearFoodName();
        clearAll();
        setNA();
        track=0;
        showAllFood(pro);
    }//GEN-LAST:event_lblrightclickMouseClicked

    private void lblleftclickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblleftclickMouseClicked
        // TODO add your handling code here:
        loc--;
        foodIndex=index-track-6;
        loc=1;
        if(foodIndex<0){
            JOptionPane.showMessageDialog(null,"You Explore All Food By Left Side");
            return;
        }
        clearFoodName();
        clearAll();
        setNA();
        track=0;
        showAllFood(pro);
    }//GEN-LAST:event_lblleftclickMouseClicked

    private void lblfood1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood1MouseClicked
        // TODO add your handling code here:
        if(lblfood1.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
        int i=Integer.parseInt(lblfood1.getName());
        ProductPojo product=pro.get(i);
        showDetails(product);
    }//GEN-LAST:event_lblfood1MouseClicked

    private void lblfood2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood2MouseClicked
        // TODO add your handling code here:
        if(lblfood2.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
        int i=Integer.parseInt(lblfood2.getName());
        ProductPojo product=pro.get(i);
        showDetails(product);
    }//GEN-LAST:event_lblfood2MouseClicked

    private void lblfood3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood3MouseClicked
        // TODO add your handling code here:
        if(lblfood3.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
        int i=Integer.parseInt(lblfood3.getName());
        ProductPojo product=pro.get(i);
        showDetails(product);
    }//GEN-LAST:event_lblfood3MouseClicked

    private void lblfood4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood4MouseClicked
        // TODO add your handling code here:
        if(lblfood4.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
       int i=Integer.parseInt(lblfood4.getName());
       ProductPojo product=pro.get(i);
       showDetails(product);
    }//GEN-LAST:event_lblfood4MouseClicked

    private void lblfood5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood5MouseClicked
        // TODO add your handling code here:
        if(lblfood5.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
        int i=Integer.parseInt(lblfood5.getName());
        ProductPojo product=pro.get(i);
        showDetails(product);
    }//GEN-LAST:event_lblfood5MouseClicked

    private void lblfood6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfood6MouseClicked
        // TODO add your handling code here:
        if(lblfood6.getName().equals("")){
          JOptionPane.showMessageDialog(null,"This is not Applicable");
          return;
        }
        int i=Integer.parseInt(lblfood5.getName());
        ProductPojo product=pro.get(i);
        showDetails(product);
    }//GEN-LAST:event_lblfood6MouseClicked

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        // TODO add your handling code here:
        new CustomerAccountFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnMyCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyCartActionPerformed
        // TODO add your handling code here:
        new CustomerCartFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMyCartActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
        new CancelOrderFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    private void btnOrderHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderHistoryActionPerformed
        // TODO add your handling code here:
        new CustomerOrderHistoryFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderHistoryActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new CustomerOptionFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnMyCart;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox<String> jcballSellerName;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblfood1;
    private javax.swing.JLabel lblfood2;
    private javax.swing.JLabel lblfood3;
    private javax.swing.JLabel lblfood4;
    private javax.swing.JLabel lblfood5;
    private javax.swing.JLabel lblfood6;
    private javax.swing.JLabel lblfoodname1;
    private javax.swing.JLabel lblfoodname2;
    private javax.swing.JLabel lblfoodname3;
    private javax.swing.JLabel lblfoodname4;
    private javax.swing.JLabel lblfoodname5;
    private javax.swing.JLabel lblfoodname6;
    private javax.swing.JLabel lblleftclick;
    private javax.swing.JLabel lblrightclick;
    // End of variables declaration//GEN-END:variables

    private void loadAllSeller() {
         try{
             allSeller=CompanyDAO.getAllSellerDetails();
             jcballSellerName.addItem("ALL");
             for(String name: allSeller.keySet()){
                 jcballSellerName.addItem(name);
             }
         }catch(SQLException sq){
             JOptionPane.showMessageDialog(null,"DB Error in Order Food Frame Loadseller");
            return;
         }
    }
    private void showAllFood(List<ProductPojo>pro) {
        for(index=foodIndex;index<pro.size()&&loc<=6;index++){
                ProductPojo product=pro.get(index);
                Image img=product.getProductImage();
                img=img.getScaledInstance(lblfood1.getWidth(),lblfood1.getHeight(),Image.SCALE_SMOOTH);        
                ImageIcon icon=new ImageIcon(img);
                if(loc==1){
                    lblfood1.setText("");
                    lblfood1.setIcon(icon);
                    lblfoodname1.setText(product.getProductName()+"");
                    lblfood1.setName(index+"");
                }
                else if(loc==2){
                    lblfood2.setText("");
                    lblfood2.setIcon(icon);
                    lblfoodname2.setText(product.getProductName()+"");
                    lblfood2.setName(index+"");
                }
                else if(loc==3){
                    lblfood3.setText("");
                    lblfood3.setIcon(icon);
                    lblfoodname3.setText(product.getProductName()+"");
                    lblfood3.setName(index+"");
                }
                else if(loc==4){
                    lblfood4.setText("");
                    lblfood4.setIcon(icon);
                    lblfoodname4.setText(product.getProductName()+"");
                    lblfood4.setName(index+"");
                }
                else if(loc==5){ 
                    lblfoodname5.setText(product.getProductName()+"");
                    lblfood5.setText("");
                    lblfood5.setIcon(icon);
                    lblfood5.setName(index+"");
                }
                else if(loc==6){
                    lblfood6.setText("");
                    lblfood6.setIcon(icon);
                    lblfoodname6.setText(product.getProductName()+"");
                    lblfood6.setName(index+"");
                }
                loc++;
                track++;
                pos++;
            }
        System.out.println("foodindex="+foodIndex);
        System.out.println("index="+index);
        System.out.println("location="+loc);
    }

    private void clearAll() {
        lblfood1.setIcon(null);
        lblfood2.setIcon(null);
        lblfood3.setIcon(null);
        lblfood4.setIcon(null);
        lblfood5.setIcon(null);
        lblfood6.setIcon(null);
        lblfoodname1.setText("");
        lblfoodname2.setText("");
        lblfoodname3.setText("");
        lblfoodname4.setText("");
        lblfoodname5.setText("");
        lblfoodname6.setText("");
  }
   private void setNA() {
        lblfood1.setText("NA");
        lblfood2.setText("NA");
        lblfood3.setText("NA");
        lblfood4.setText("NA");
        lblfood5.setText("NA");
        lblfood6.setText("NA");
        lblfoodname1.setText("NA");
        lblfoodname2.setText("NA");
        lblfoodname3.setText("NA");
        lblfoodname4.setText("NA");
        lblfoodname5.setText("NA");
        lblfoodname6.setText("NA");
} 
private void clearFoodName(){
    lblfood1.setName("");
    lblfood2.setName("");
    lblfood3.setName("");
    lblfood4.setName("");
    lblfood5.setName("");
    lblfood6.setName("");
}
   private void showDetails(ProductPojo product){
       Object parentComponent = null;

        // Message to be displayed
        String Seller=jcballSellerName.getSelectedItem().toString();
        if(jcballSellerName.getSelectedItem().toString().equals("ALL")){
            String id=product.getCompanyId();
            for (Map.Entry<String, String> entry : allSeller.entrySet()) {
                if(entry.getValue().equals(id)){
                    Seller=entry.getKey();
                }
                
            }
        }
        String message = "Food Name:-"+ product.getProductName() +"\n" +"Food Price:-"+product.getProductPrice()+"\n"+"Seller Name:-"+Seller;

        // Dialog title
        String title = "Confirmation";

        // Option type (YES_NO_OPTION, YES_NO_CANCEL_OPTION, OK_CANCEL_OPTION)
        int optionType = JOptionPane.YES_NO_OPTION;

        // Icon type (QUESTION_MESSAGE, INFORMATION_MESSAGE, WARNING_MESSAGE, ERROR_MESSAGE, PLAIN_MESSAGE)
        int messageType = JOptionPane.QUESTION_MESSAGE;

        // Options (buttons)
        Object[] options = {"Order_Now", "Add_To_Cart"};

        // Show the dialog and capture the user's choice
        int userChoice = JOptionPane.showOptionDialog((Component) parentComponent,
                message,
                title,
                optionType,
                messageType,
                null,  // icon (null for default)
                options,  // options (buttons)
                options[0]  // default option
        );

        // Process the user's choice
        if (userChoice == JOptionPane.YES_OPTION) {
            OrderProductFrame orderProductFrame=new OrderProductFrame(product);
            orderProductFrame.setVisible(true);
            this.dispose();
        } else if (userChoice == JOptionPane.NO_OPTION) {
            try{
                PlaceOrderPojo placeOrderPojo=new PlaceOrderPojo();
                placeOrderPojo.setCompanyId(product.getCompanyId());
                placeOrderPojo.setProductId(product.getProductId());
                placeOrderPojo.setCustomerId(UserProfile.getUserId());
                placeOrderPojo.setStaffId(StaffDAO.getRandomStaffId(product.getCompanyId()));
                if(PlaceOrderDAO.placeOrderforCart(placeOrderPojo)){
                   JOptionPane.showMessageDialog(null,"Product Added in Cart Succesfully");
                   return;
                }else{
                    JOptionPane.showMessageDialog(null,"Cant Add Product In Cart");
                    return;
                }
            }catch(SQLException sq){
             JOptionPane.showMessageDialog(null,"DB Error in Order Food Frame For Add to Cart");
            return;
         } 
       }
        else {
            System.out.println("User closed the dialog");
            // Perform actions for dialog close or other options
        }

   }
}
