/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yumxpress.gui;

import java.awt.Image;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import yumxpress.dao.ProductDAO;
import yumxpress.pojo.ProductPojo;
import yumxpress.util.OwnerProfile;

/**
 *
 * @author Smart computer
 */
public class ViewFoodFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewFoodFrame
     */
    Map<String,ProductPojo> products=new HashMap<>();
    public ViewFoodFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userNameHii1.setText("Hello "+OwnerProfile.getOwnerName());
        loadProductDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcbSelectFood = new javax.swing.JComboBox<>();
        lblfoodimg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFoodPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addStaff = new javax.swing.JButton();
        viewStaff = new javax.swing.JButton();
        addFood = new javax.swing.JButton();
        orderList = new javax.swing.JButton();
        back = new javax.swing.JButton();
        userNameHii1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(129, 120, 177));
        jLabel2.setText("View Food");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        jcbSelectFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jcbSelectFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSelectFoodActionPerformed(evt);
            }
        });
        jPanel2.add(jcbSelectFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 331, 31));
        jPanel2.add(lblfoodimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 364, 240));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(129, 120, 177));
        jLabel3.setText("Price:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 550, 82, 25));

        txtFoodPrice.setEditable(false);
        txtFoodPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtFoodPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFoodPriceActionPerformed(evt);
            }
        });
        jPanel2.add(txtFoodPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 550, 229, 31));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(129, 120, 177));
        jLabel4.setText("Select Food Name");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jPanel1.setBackground(new java.awt.Color(129, 120, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yumxpress/icons/user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 16, -1, -1));

        addStaff.setBackground(new java.awt.Color(153, 255, 102));
        addStaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addStaff.setText("Add Staff");
        addStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffActionPerformed(evt);
            }
        });
        jPanel1.add(addStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 248, 187, 41));

        viewStaff.setBackground(new java.awt.Color(153, 255, 102));
        viewStaff.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewStaff.setText("View Staff");
        viewStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStaffActionPerformed(evt);
            }
        });
        jPanel1.add(viewStaff, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 328, 187, 40));

        addFood.setBackground(new java.awt.Color(153, 255, 102));
        addFood.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addFood.setText("Add Food");
        addFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFoodActionPerformed(evt);
            }
        });
        jPanel1.add(addFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 407, 187, 40));

        orderList.setBackground(new java.awt.Color(153, 255, 102));
        orderList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        orderList.setText("Order List");
        orderList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderListActionPerformed(evt);
            }
        });
        jPanel1.add(orderList, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 484, 187, 40));

        back.setBackground(new java.awt.Color(153, 255, 102));
        back.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 565, 106, 36));

        userNameHii1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        userNameHii1.setForeground(new java.awt.Color(255, 255, 255));
        userNameHii1.setText("@NULL");
        jPanel1.add(userNameHii1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 175, 215, 36));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, 290, 13));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 649, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffActionPerformed
        // TODO add your handling code here:
        AddDeliveryStaffFrame addStaffFrame=new AddDeliveryStaffFrame();
        addStaffFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addStaffActionPerformed

    private void addFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFoodActionPerformed
        // TODO add your handling code here:
        AddFoodItemFrame addFoodItemFrame=new AddFoodItemFrame();
        addFoodItemFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addFoodActionPerformed

    private void orderListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderListActionPerformed
        // TODO add your handling code here:
        SellerOrderListFrame orderListFrame=new SellerOrderListFrame();
        orderListFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_orderListActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        SellerOptionsFrame sellerOptionFrame=new SellerOptionsFrame();
        sellerOptionFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jcbSelectFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSelectFoodActionPerformed
        // TODO add your handling code here:
        String selectedfood=jcbSelectFood.getSelectedItem().toString();
        ProductPojo product = products.get(selectedfood);
        Image img=product.getProductImage();
        img=img.getScaledInstance(lblfoodimg.getWidth(),lblfoodimg.getHeight(),Image.SCALE_SMOOTH);        
        ImageIcon icon=new ImageIcon(img);
        lblfoodimg.setIcon(icon);
        txtFoodPrice.setText(product.getProductPrice()+"");
    }//GEN-LAST:event_jcbSelectFoodActionPerformed

    private void txtFoodPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFoodPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFoodPriceActionPerformed

    private void viewStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStaffActionPerformed
        // TODO add your handling code here:
        ViewDeliveryStaffFrame viewDeliveryStaffFram=new ViewDeliveryStaffFrame();
        viewDeliveryStaffFram.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewFoodFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewFoodFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addFood;
    private javax.swing.JButton addStaff;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> jcbSelectFood;
    private javax.swing.JLabel lblfoodimg;
    private javax.swing.JButton orderList;
    private javax.swing.JTextField txtFoodPrice;
    private javax.swing.JLabel userNameHii1;
    private javax.swing.JButton viewStaff;
    // End of variables declaration//GEN-END:variables

    private void loadProductDetails() {
         try{
            products=ProductDAO.getProductDetailsByCompanyId(OwnerProfile.getCompanyId().trim());
            if(products.isEmpty()){
                JOptionPane.showMessageDialog(null,"No Products Added Yet");
                return;
            }
        showProductsName();
        }catch(SQLException sq){
            JOptionPane.showMessageDialog(null,"DB Error in View Food Frame");
            return;
        }
         catch(IOException sq){
            JOptionPane.showMessageDialog(null,"I/O Error in View Food Frame");
            return;
        }
    }

    private void showProductsName() {
        for(String productName : products.keySet()){
                this.jcbSelectFood.addItem(productName);
            }
    }
}
